[package]
name = "wex"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
which = "7.0"
dirs = "6.0"
anyhow = "1.0"
heck = "0.5"
regex = "1.11"
pomsky = "0.11"
